apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ngx-lua.fullname" . }}-secret
  labels:
    {{- include "ngx-lua.labels" . | nindent 4 }}
type: Opaque
data:
  header-value: {{ .Values.env.HEADER_SECRET_VALUE | b64enc }}
