apiVersion: v1
kind: Service
metadata:
  name: {{ include "ngx-lua.fullname" . }}
  labels:
    {{- include "ngx-lua.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: {{ include "ngx-lua.name" . }}
